/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Denis' at '01.06.16 16:35' with Gradle 2.9
 *
 * @author Denis, @date 01.06.16 16:35
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
