version: 0.0
os: linux
files:
  - source: vertx-h2-jdo
    destination: /opt/vertx
permissions:
  - object: /opt/vertx
    mode: 777
    type:
      - directory
hooks:
  ApplicationStart:
    - location: /opt/vertx/vertx-h2-jdo/bin/vertx-h2-jdo
      timeout: 300