version: 0.0
os: linux
files:
  - source: vertx-h2-jdo
    destination: /opt/vertx
permissions:
  - object: /opt
    pattern: "vertx"
    mode: 777
    type:
      - directory
hooks:
  ApplicationStop:
    - location: deployScripts/stop
      timeout: 10
  ApplicationStart:
    - location: deployScripts/start
      timeout: 300